[package]
name = "xlsx2csv"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
csv = "1.3"
quick-xml = "0.31"
regex = "1.10"
zip = { version = "2.4", default-features = false, features = ["deflate"] }
